/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedOrderIndexRouteImport } from './routes/_protected/order/index'
import { Route as ProtectedMenuIndexRouteImport } from './routes/_protected/menu/index'
import { Route as ProtectedMenuEditRouteImport } from './routes/_protected/menu/edit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrderIndexRoute = ProtectedOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMenuIndexRoute = ProtectedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMenuEditRoute = ProtectedMenuEditRouteImport.update({
  id: '/menu/edit',
  path: '/menu/edit',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof ProtectedIndexRoute
  '/menu/edit': typeof ProtectedMenuEditRoute
  '/menu': typeof ProtectedMenuIndexRoute
  '/order': typeof ProtectedOrderIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof ProtectedIndexRoute
  '/menu/edit': typeof ProtectedMenuEditRoute
  '/menu': typeof ProtectedMenuIndexRoute
  '/order': typeof ProtectedOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/menu/edit': typeof ProtectedMenuEditRoute
  '/_protected/menu/': typeof ProtectedMenuIndexRoute
  '/_protected/order/': typeof ProtectedOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth/login' | '/' | '/menu/edit' | '/menu' | '/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/login' | '/' | '/menu/edit' | '/menu' | '/order'
  id:
    | '__root__'
    | '/_protected'
    | '/auth/login'
    | '/_protected/'
    | '/_protected/menu/edit'
    | '/_protected/menu/'
    | '/_protected/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/order/': {
      id: '/_protected/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof ProtectedOrderIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/menu/': {
      id: '/_protected/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof ProtectedMenuIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/menu/edit': {
      id: '/_protected/menu/edit'
      path: '/menu/edit'
      fullPath: '/menu/edit'
      preLoaderRoute: typeof ProtectedMenuEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedMenuEditRoute: typeof ProtectedMenuEditRoute
  ProtectedMenuIndexRoute: typeof ProtectedMenuIndexRoute
  ProtectedOrderIndexRoute: typeof ProtectedOrderIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedMenuEditRoute: ProtectedMenuEditRoute,
  ProtectedMenuIndexRoute: ProtectedMenuIndexRoute,
  ProtectedOrderIndexRoute: ProtectedOrderIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
