/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedOrderIndexRouteImport } from './routes/_protected/order/index'
import { Route as ProtectedMenuIndexRouteImport } from './routes/_protected/menu/index'
import { Route as ProtectedKitchenIndexRouteImport } from './routes/_protected/kitchen/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrderIndexRoute = ProtectedOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMenuIndexRoute = ProtectedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKitchenIndexRoute = ProtectedKitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof ProtectedIndexRoute
  '/kitchen': typeof ProtectedKitchenIndexRoute
  '/menu': typeof ProtectedMenuIndexRoute
  '/order': typeof ProtectedOrderIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof ProtectedIndexRoute
  '/kitchen': typeof ProtectedKitchenIndexRoute
  '/menu': typeof ProtectedMenuIndexRoute
  '/order': typeof ProtectedOrderIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/kitchen/': typeof ProtectedKitchenIndexRoute
  '/_protected/menu/': typeof ProtectedMenuIndexRoute
  '/_protected/order/': typeof ProtectedOrderIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth/login' | '/' | '/kitchen' | '/menu' | '/order' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/login' | '/' | '/kitchen' | '/menu' | '/order' | '/users'
  id:
    | '__root__'
    | '/_protected'
    | '/auth/login'
    | '/_protected/'
    | '/_protected/kitchen/'
    | '/_protected/menu/'
    | '/_protected/order/'
    | '/_protected/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/order/': {
      id: '/_protected/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof ProtectedOrderIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/menu/': {
      id: '/_protected/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof ProtectedMenuIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/kitchen/': {
      id: '/_protected/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof ProtectedKitchenIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedKitchenIndexRoute: typeof ProtectedKitchenIndexRoute
  ProtectedMenuIndexRoute: typeof ProtectedMenuIndexRoute
  ProtectedOrderIndexRoute: typeof ProtectedOrderIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedKitchenIndexRoute: ProtectedKitchenIndexRoute,
  ProtectedMenuIndexRoute: ProtectedMenuIndexRoute,
  ProtectedOrderIndexRoute: ProtectedOrderIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
